PUNCHBOOT_VERSION = 97ae3387ee3b930ad8d8ad9e877281389589d2c1
PUNCHBOOT_SITE = https://github.com/jonasblixt/punchboot.git
PUNCHBOOT_SITE_METHOD = git
PUNCHBOOT_INSTALL_STAGING = YES
PUNCHBOOT_LICENSE = BSD-3-Clause
PUNCHBOOT_LICENSE_FILES = License.txt
PUNCHBOOT_INSTALL_IMAGES = YES
PUNCHBOOT_DEPENDENCIES = host-bpak

define PUNCHBOOT_CONFIGURE_CMDS
		cp $(BR2_PUNCHBOOT_DEFCONFIG) $(@D)/.config
endef

define PUNCHBOOT_BUILD_CMDS
	$(MAKE) -C $(@D)/
endef

define PUNCHBOOT_INSTALL_IMAGES_CMDS
	$(MAKE) -C $(@D)/ install INSTALL_DIR=$(BINARIES_DIR)
endef

$(eval $(generic-package))
